version: '3.8'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Europe/Budapest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    networks:
      opt_net:
        ipv4_address: 172.20.0.1
    
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    #devices:
      #- /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host
  
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /opt/plex_server/config:/config
      - /opt/plex_server/tv:/tv
      - /opt/plex_server/movies:/movies
    restart: unless-stopped
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - /opt/mosquitto:/mosquitto
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      opt_net:
        ipv4_address: 172.20.0.2

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /opt/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Budapest
    devices:
      # Make sure this matched your adapter location
      #- /dev/ttyUSB0:/dev/ttyACM0
      - /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_c6fdc1b5575aed11ba09f1165820eef3-if00-port0:/dev/ttyACM0
    networks:
      opt_net:
        ipv4_address: 172.20.0.3

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    networks:
      opt_net:
        ipv4_address: 172.20.0.4
        
  appdaemon:
    container_name: appdaemon
    restart: unless-stopped
    image: acockburn/appdaemon:latest
    environment:
      - TZ=Europe/Berlin
      - HA_URL=http://homeassistant:8123
      - TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwODAzYWU1NzdjODg0M2Q4OTBhYjNhYTBlMzdhZTNjZiIsImlhdCI6MTcwMjY1NDgyNywiZXhwIjoyMDE4MDE0ODI3fQ.7w2PoTXwJsd856baEZwjoaJVt1KXABS0Iqol65cDlSA
    ports:
      - "5050:5050"
    volumes:
      - /opt/appdeamon/conf:/conf
    networks:
      opt_net:

networks:
  opt_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          #docker-compose v3+ do not use ip_range
          #ip_range: 172.28.5.0/24
